language: node_js

node_js:
    - "8.11.3"

cache:
    directories:
        - node_modules

install:
    - npm install

script:
    - npm run test
    - npm run build

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run test:coveralls
