language: node_js

node_js:
    - "8.11.3"

cache:
    directories:
        - node_modules

before_install: cd static

install:
    - npm install

script:
    - npm run lint:css
    - npm run lint:js
    - npm run flow
    - npm run test:coveralls
    - npm run build
